const menuItems = [
  {
    id: 1,
    title: 'Soup and Salad',
    category: 'breakfast',
    price: 9.99,
    img: './images/item-1.jpeg',
    desc: `Your choice of Baked Potato Soup, Soup of the Day or French Onion Soup (for an additional charge). Caesar Side Salad, House Side Salad or Premium Side Salads (for an additional charge) `,
  },
  {
    id: 2,
    title: 'Prime Rib Sandwich',
    category: 'lunch',
    price: 11.99,
    img: './images/item-2.jpeg',
    desc: `Lunch size tender slow-roasted prime rib, grilled onions and mushrooms, Provolone cheese, and our spicy signature bloom sauce on a toasted baguette.`,
  },
  {
    id: 3,
    title: 'Bloomin Onion®',
    category: 'appetizer',
    price: 9.49,
    img: './images/item-16.jpeg',
    desc: `Our special onion is hand-carved, cooked until golden and ready to dip into our spicy signature bloom sauce.`,
  },
  {
    id: 4,
    title: 'country delight',
    category: 'breakfast',
    price: 20.99,
    img: './images/item-4.jpeg',
    desc: `Shabby chic keffiyeh neutra snackwave pork belly shoreditch. Prism austin mlkshk truffaut, `,
  },
  {
    id: 5,
    title: 'egg attack',
    category: 'lunch',
    price: 22.99,
    img: './images/item-5.jpeg',
    desc: `franzen vegan pabst bicycle rights kickstarter pinterest meditation farm-to-table 90's pop-up `,
  },
  {
    id: 6,
    title: 'oreo dream',
    category: 'shakes',
    price: 18.99,
    img: './images/item-6.jpeg',
    desc: `Portland chicharrones ethical edison bulb, palo santo craft beer chia heirloom iPhone everyday`,
  },
  {
    id: 7,
    title: 'bacon overflow',
    category: 'breakfast',
    price: 8.99,
    img: './images/item-7.jpeg',
    desc: `carry jianbing normcore freegan. Viral single-origin coffee live-edge, pork belly cloud bread iceland put a bird `,
  },
  {
    id: 8,
    title: 'american classic',
    category: 'lunch',
    price: 12.99,
    img: './images/item-8.jpeg',
    desc: `on it tumblr kickstarter thundercats migas everyday carry squid palo santo leggings. Food truck truffaut  `,
  },
  {
    id: 9,
    title: 'Buddys Shake',
    category: 'shakes',
    price: 16.99,
    img: './images/item-9.jpeg',
    desc: `CHOCOLATE, STRAWBERRY and VANILLA MADE WITH REAL ICE CREAM`,
  },
  {
    id: 10,
    title: ' Kingsland Pasta',
    category: 'dinner',
    price: 25.99,
    img: './images/item-11.jpeg',
    desc: `A steakhouse twist on your favorite Queensland Pasta. Grilled steak and shrimp over fettuccine noodles tossed in a bold Alfredo sauce..`,
  },
  {
    id: 12,
    title: ' Center-Cut Sirloin',
    category: 'dinner',
    price: 22.99,
    img: './images/item-12.jpeg',
    desc: `Center-cut for tenderness. Lean, hearty and full of flavor. Seasoned and seared. Served with two freshly made sides.(11oz)`,
  },
  {
    id: 13,
    title: 'Bone-In Ribeye* 18 oz.',
    category: 'dinner',
    price: 33.49,
    img: './images/item-13.jpeg',
    desc: `Bone-in and extra marbled for maximum tenderness. Served with two freshly made sides. `,
  },
  {
    id: 14,
    title: 'Spinach Dip',
    category: 'appetizer',
    price: 9.99,
    img: './images/item-14.jpeg',
    desc: `Cheesy and creamy spinach topped with melted Jack and Cheddar cheeses. Served with tortilla chips for dipping`,
  },
  {
    id: 15,
    title: 'Savory Party Bread',
    category: 'appetizer',
    price: 9.99,
    img: './images/item-15.jpeg',
    desc: `It's impossible to stop nibbling on warm pieces of this cheesy, oniony bread. The sliced loaf fans out for a fun presentatio`,
  }
]


export default menuItems;